### ISSUE TITLE
Installed ewstools using pip but shows AttributeError

### ISSUE THREAD

**Issue by gabosantos** [ThomasMBury/ewstools#428]
Hi,

I am exploring this library for my research on detecting tipping points.  I made a time-series data based on typhoon speeds and would like to run it through this module.  I am following the tutorial notebook where the time series class was initiated but this is where I encountered the AttributeError.  Screenshot shown below:

![image](https://user-images.githubusercontent.com/2747117/177730227-a5beb6b9-6f56-42cf-98b1-dfd71dbb2cf6.png)

I wonder if there's a suggested fix on this? Thanks and hope to hear from you soon.

Regards,
Gabriel

**Comment by ThomasMBury** [comment]
Hi Gabriel,

I’m following up on this old issue because I’m currently preparing grant proposals to support the continued maintenance and development of ewstools.

I’m working on this with Bruce Stephenson, a software engineer who has been contributing fixes and helping improve the package’s architecture.

Were you ultimately able to use ewstools for your typhoon tipping-point research? I’d be very interested to hear what you found useful, what caused difficulties, and whether you needed to write additional code or use other tools alongside it.

Even a brief response would be very helpful. Thanks again!
