### ISSUE TITLE
Spectral EWS tutorial link

### ISSUE THREAD

**Issue by alxgom** [ThomasMBury/ewstools#429]
Hi, 
The link for the spectral EWS tutorial in the pypi page, and the jupyter notebook link in https://pypi.org/project/ewstools/1.0.1/#demos don't work. 

Thanks for the hard work ;)
Alexis

**Comment by ThomasMBury** [comment]
Thanks for noticing this Alexis. The reason for this is because the links in the README are defined locally to the Github repository. This same README is also used on PyPI, hence the links don't work there. I've now made the links global, so they should also work on PyPI. However, this change will only happen when I release a new version of ewstools to PyPI - until then :)

**Comment by ThomasMBury** [comment]
The links in the README are now defined globally, so they should also work on the PyPI page with this new release (2.1.0). Thanks again for posting this.
Tom
